from datetime import datetime
from typing import Optional

from pydantic import BaseModel, computed_field


class CourseSegmentResponse(BaseModel):
    segment_index: int
    start_distance_m: float
    end_distance_m: float
    length_m: float
    avg_gradient: float
    elevation_change_m: float
    segment_type: str
    power_w: Optional[float] = None
    speed_ms: Optional[float] = None
    duration_s: Optional[float] = None
    start_offset_s: Optional[float] = None
    speed_capped: bool = False

    model_config = {"from_attributes": True}


class CourseSummaryResponse(BaseModel):
    id: str
    name: str
    goal_id: Optional[str] = None
    bike_id: Optional[str] = None
    status: str
    distance_m: float
    elevation_gain_m: Optional[float] = None
    target_time_s: Optional[int] = None
    start_time: Optional[datetime] = None
    predicted_time_s: Optional[float] = None
    feasible: Optional[bool] = None
    refusal_reason: Optional[str] = None
    plan_status: Optional[str] = None
    created_at: datetime

    model_config = {"from_attributes": True}


class CourseDetailResponse(CourseSummaryResponse):
    error: Optional[str] = None
    ftp_w_used: Optional[float] = None
    weight_kg_used: Optional[float] = None
    elevation_loss_m: Optional[float] = None
    min_elevation_m: Optional[float] = None
    max_elevation_m: Optional[float] = None
    intensity: Optional[float] = None
    required_intensity: Optional[float] = None
    # ≤400 × [distance_m, elevation_m, gradient] — the chart payload. The
    # course's *track* (coordinates) is deliberately absent from every
    # response shape in this module.
    profile: Optional[list] = None
    segments: list[CourseSegmentResponse] = []


class CourseReanalyzeBody(BaseModel):
    """Partial update for re-analysis. A field left unset keeps the stored
    value; an explicit null clears it (goal, target time, start time)."""

    bike_id: Optional[str] = None
    goal_id: Optional[str] = None
    target_time_s: Optional[int] = None
    start_time: Optional[datetime] = None


class CoursePlanBody(BaseModel):
    locale: Optional[str] = None


class CoursePlanResponse(BaseModel):
    status: Optional[str] = None
    mood: Optional[str] = None
    plan: Optional[str] = None
    updated_at: Optional[datetime] = None

    # Issue #41 AI disclosure — same derivation as GoalGuidanceResponse.
    @computed_field  # type: ignore[prop-decorator]
    @property
    def plan_ai_generated(self) -> bool:
        """True when `plan` was generated by a language model."""
        return bool(self.plan)
