from datetime import date, datetime
from typing import Optional

from pydantic import BaseModel, computed_field


class GoalCreate(BaseModel):
    title: str
    description: Optional[str] = None
    target_date: Optional[date] = None
    metric: Optional[str] = None
    target_value: Optional[float] = None


class GoalUpdate(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None
    target_date: Optional[date] = None
    metric: Optional[str] = None
    target_value: Optional[float] = None
    current_value: Optional[float] = None
    status: Optional[str] = None
    outcome_note: Optional[str] = None


class GoalResponse(BaseModel):
    id: str
    athlete_id: str
    title: str
    description: Optional[str] = None
    target_date: Optional[date] = None
    metric: Optional[str] = None
    target_value: Optional[float] = None
    current_value: Optional[float] = None
    status: str
    outcome_note: Optional[str] = None
    created_at: datetime

    model_config = {"from_attributes": True}


class GoalGuidanceBody(BaseModel):
    locale: Optional[str] = None


class GoalGuidanceResponse(BaseModel):
    status: Optional[str] = None
    verdict: Optional[str] = None
    guidance: Optional[str] = None
    updated_at: Optional[datetime] = None

    # Issue #41. `verdict` is parsed out of the same model call that writes
    # `guidance`, so one flag covers the pair. See
    # `TrainingStatusResponse.feedback_ai_generated` for why it is derived
    # rather than stored.
    @computed_field  # type: ignore[prop-decorator]
    @property
    def guidance_ai_generated(self) -> bool:
        """True when `guidance` and `verdict` were generated by a language model."""
        return bool(self.guidance)
